/**
 * downloadPdf.js
 * Reliable PDF download utility for Vite + React.
 * Uses jsPDF text rendering — no html2canvas, no DOM capture, no CORS issues.
 */

import { jsPDF } from "jspdf";

/** Strip markdown syntax for clean PDF text */
const stripMarkdown = (text) =>
  text
    .replace(/#{1,6}\s+/g, "")
    .replace(/\*\*(.+?)\*\*/g, "$1")
    .replace(/\*(.+?)\*/g, "$1")
    .replace(/`{1,3}[^`\n]*`{1,3}/g, "")
    .replace(/\[(.+?)\]\(.+?\)/g, "$1")
    .replace(/^\s*[-*+]\s+/gm, "• ")
    .replace(/^\s*\d+\.\s+/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();

/**
 * Downloads summary text as a formatted A4 PDF.
 *
 * @param {string} summaryText  - Markdown or plain text content
 * @param {string} title        - Document title shown at top
 * @param {string} filename     - Output filename (default: "summary.pdf")
 */
export const downloadSummaryAsPdf = (
  summaryText,
  title = "Summary",
  filename = "summary.pdf"
) => {
  if (!summaryText?.trim()) {
    console.warn("downloadSummaryAsPdf: no content");
    return;
  }

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const mL = 18;   // margin left
  const mR = 18;   // margin right
  const mT = 16;   // margin top (after header)
  const mB = 16;   // margin bottom
  const contentW = pageW - mL - mR;

  // ── Helper: add a new page with a thin header ────────────────────────────
  const addPageHeader = () => {
    doc.addPage();
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageW, 10, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text("Briefly", mL, 7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(51, 65, 85);
    return mT + 10; // y position after header
  };

  let y = 0;

  // ── Page 1 header bar ────────────────────────────────────────────────────
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 12, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(255, 255, 255);
  doc.text("Briefly", mL, 8.5);

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(dateStr, pageW - mR, 8.5, { align: "right" });

  y = 22;

  // ── Title ────────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  const titleLines = doc.splitTextToSize(title, contentW);
  doc.text(titleLines, mL, y);
  y += titleLines.length * 9 + 3;

  // Divider
  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.5);
  doc.line(mL, y, pageW - mR, y);
  y += 7;

  // ── Body ─────────────────────────────────────────────────────────────────
  const cleanText = stripMarkdown(summaryText);
  const paragraphs = cleanText.split("\n");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(51, 65, 85);
  const lineH = 6.2;

  for (const para of paragraphs) {
    if (para.trim() === "") {
      y += lineH * 0.5; // blank line gap
      continue;
    }

    // Detect headings (lines starting with •  or ALL CAPS short lines)
    const isHeading = para.length < 80 && para === para.toUpperCase() && para.trim().length > 3;
    const isBullet = para.startsWith("•");

    if (isHeading) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
    } else if (isBullet) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
    } else {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
    }

    const indent = isBullet ? mL + 4 : mL;
    const width = isBullet ? contentW - 4 : contentW;
    const lines = doc.splitTextToSize(para, width);

    for (const line of lines) {
      if (y + lineH > pageH - mB) {
        y = addPageHeader();
        doc.setFont("helvetica", "normal");
        doc.setFontSize(11);
        doc.setTextColor(51, 65, 85);
      }
      doc.text(line, indent, y);
      y += lineH;
    }

    // Reset font after heading
    if (isHeading) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      y += 1;
    }
  }

  // ── Footer on last page ──────────────────────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Generated by Briefly AI  •  Page ${i} of ${totalPages}`,
      pageW / 2,
      pageH - 8,
      { align: "center" }
    );
  }

  doc.save(filename);
};